/*
 * Copyright (c) 2015 VMware, Inc.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR
 * A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hyperic_hq_pdh_MultipleCollectQueryPdh */

#ifndef _Included_org_hyperic_hq_pdh_MultipleCollectQueryPdh
#define _Included_org_hyperic_hq_pdh_MultipleCollectQueryPdh
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_hyperic_hq_pdh_MultipleCollectQueryPdh
	* Method:    pdhOpenQuery
	* Signature: ()J
	*/
	JNIEXPORT jlong JNICALL Java_org_hyperic_hq_pdh_MultipleCollectQueryPdh_pdhOpenQuery
		(JNIEnv *, jclass);

	/*
	* Class:     org_hyperic_hq_pdh_MultipleCollectQueryPdh
	* Method:    pdhAddCounter
	* Signature: (JLjava/lang/String;)J
	*/
	JNIEXPORT jlong JNICALL Java_org_hyperic_hq_pdh_MultipleCollectQueryPdh_pdhAddCounter
		(JNIEnv *, jclass, jlong, jstring);

	/*
	* Class:     org_hyperic_hq_pdh_MultipleCollectQueryPdh
	* Method:    pdhRemoveCounter
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_org_hyperic_hq_pdh_MultipleCollectQueryPdh_pdhRemoveCounter
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     org_hyperic_hq_pdh_MultipleCollectQueryPdh
	* Method:    PdhCollectQueryData
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_org_hyperic_hq_pdh_MultipleCollectQueryPdh_PdhCollectQueryData
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     org_hyperic_hq_pdh_MultipleCollectQueryPdh
	* Method:    PdhGetFormattedCounterValue
	* Signature: (J)D
	*/
	JNIEXPORT jdouble JNICALL Java_org_hyperic_hq_pdh_MultipleCollectQueryPdh_PdhGetFormattedCounterValue
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     org_hyperic_hq_pdh_MultipleCollectQueryPdh
	* Method:    pdhGetInstances
	* Signature: (Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_org_hyperic_hq_pdh_MultipleCollectQueryPdh_pdhGetInstances
		(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
